apiVersion: {{ include "networkpolicyversion" . }}
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from pods labeled with 'networking.gardener.cloud/to-private-except-metadata-cluster=allowed'
      to the Private networks (RFC1918), Carrier-grade NAT (RFC 6598) except for CloudProvider's specific metadata service IP,
      Seed and Shoot networks.
  name: allow-to-private-except-metadata-cluster
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-private-except-metadata-cluster: allowed
  egress:
  - to:
{{- range $i, $network := .Values.privateNetworks }}
    - ipBlock:
        cidr: {{ required ".network.cidr is required" $network.network }}
{{- if $network.except }}
        except:
{{ toYaml $network.except | indent 8 }}
{{- end }}
{{- end }}
  policyTypes:
  - Egress
  ingress: []
